version: '3.8'

services:
  python-gpu-container-gpu0:
    build:
      context: . # Path to the Dockerfile (current directory)
      dockerfile: Dockerfile
    shm_size: '128g'
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: "0"  # Restrict to GPU 0
      CUDA_HOME: "/usr/local/cuda"
      LD_LIBRARY_PATH: "/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
    volumes:
      - /home/siedel/data:/data
      - /home/siedel/trained_models:/trained_models
      - ./results:/workspace/results
      - ./experiments/configs:/workspace/experiments/configs
      - ./run_exp.py:/workspace/run_exp.py
      - ./run_exp_1.py:/workspace/run_exp_1.py
      - ./run_exp_2.py:/workspace/run_exp_2.py
      - ./run_exp_3.py:/workspace/run_exp_3.py
    command: ["taskset", "-c", "32-39", "/bin/bash"]
    #command: python run_exp.py  # Run the main script for this container
    tty: true

  python-gpu-container-gpu1:
    extends:
      service: python-gpu-container-gpu0
    environment:
      NVIDIA_VISIBLE_DEVICES: "1"  # Restrict to GPU 1
    command: ["taskset", "-c", "40-47", "/bin/bash"]
    #command: python run_exp_1.py  # Run a different script for this container
    tty: true

  python-gpu-container-gpu2:
    extends:
      service: python-gpu-container-gpu0
    environment:
      NVIDIA_VISIBLE_DEVICES: "2"  # Restrict to GPU 2
    command: ["taskset", "-c", "48-55", "/bin/bash"]
    #command: python run_exp_2.py  # Run a different script for this container
    tty: true

  python-gpu-container-gpu3:
    extends:
      service: python-gpu-container-gpu0
    environment:
      NVIDIA_VISIBLE_DEVICES: "3"  # Restrict to GPU 3
    command: ["taskset", "-c", "56-63", "/bin/bash"] 
    #command: python run_exp_3.py  # Run a different script for this container
    tty: true
